# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boot.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 720)
        MainWindow.setMinimumSize(QtCore.QSize(720, 720))
        MainWindow.setMaximumSize(QtCore.QSize(720, 720))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.viewport = QtWidgets.QWidget(MainWindow)
        self.viewport.setMinimumSize(QtCore.QSize(720, 720))
        self.viewport.setMaximumSize(QtCore.QSize(720, 720))
        self.viewport.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.viewport.setToolTip("")
        self.viewport.setObjectName("viewport")
        self.image = QtWidgets.QLabel(self.viewport)
        self.image.setGeometry(QtCore.QRect(0, 0, 720, 720))
        self.image.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        MainWindow.setCentralWidget(self.viewport)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
